# Informações do Site
title: Xavier | Software Engineering & Data Analysis
email: pedrohenriquereisxavier@gmail.com
description: >- 
  Portfólio de Pedro Henrique Reis Xavier. Estudante de Engenharia de Software no IFPE, 
  entusiasta de Análise de Dados e Inovação com Sotaque Pernambucano.
baseurl: ""
url: "https://xavier9190.github.io"
markdown: kramdown
theme: jekyll-theme-minimal 
